ignore: []
rule_settings:
  enable:
    - default
  disable:
    - do-not-use-bare-except
  rule_types:
    - refactoring
    - suggestion
    - comment
  python_version: "3.11"

rules: []

metrics:
  quality_threshold: 20.0

clone_detection:
  min_lines: 3
  min_duplicates: 2
  identical_clones_only: false

github:
  labels: []
  ignore_labels: [sourcery-ignore]
  request_review: author
  sourcery_branch: sourcery/{base_branch}
