all_extensions:
  - cogs.actions
  - cogs.api
  - cogs.config
  - cogs.fun
  - cogs.holidays
  - cogs.holidays.easter
  - cogs.ipc
  - cogs.love
  - cogs.memegen
  - cogs.meta
  - cogs.mis
  - cogs.mod
  - cogs.music
  - cogs.nasa
  - cogs.nsfw
  - cogs.owner
  - cogs.rtfm
  - cogs.sports
  - cogs.telephone
  - cogs.twitter
  - cogs.ticket
  - cogs.utils
  - cogs.wolfram
  - events.custom_events
  - events.guild.channel
  - events.guild.extra
  - events.guild.join
  - events.guild.member
  - events.guild.role_emoji
  - events.guild.thread
  - events.on_cmd
  - events.on_msg
  - events.on_rexn
  - events.user
  - interactions.buttons
  - interactions.buttons.foggle
  - interactions.buttons.snakes
  - interactions.slash
  - jishaku
  - custom_commands
  - cogs.highlight

dev_logo: >-
  https://raw.githubusercontent.com/rtk-rnjn/Parrot/main/extra/kali.png
