[tool.poetry]
name = "parrot"
version = "0.1.0"
description = ""
authors = ["repl.it user <replituser@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1.2"
youtube-dl = "^2021.4.7"
markdownify = "^0.6.5"
aiohttp = "^3.7.4"
bs4 = "^0.0.1"
psutil = "^5.8.0"
disputils = "^0.1.3"
async-timeout = "^3.0.1"
discord = "^1.0.1"
jishaku = "^1.20.0"
utils = "^1.0.1"
editdistance = "^0.5.3"
pymongo = "^3.11.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
