[tool.black]
line-length = 125
skip-string-normalization = true

[tool.isort]
profile = "black"
combine_as_imports = true
combine_star = true
line_length = 125

[tool.pyright]
reportUnnecessaryTypeIgnoreComment = "warning"
pythonVersion = "3.11"
typeCheckingMode = "basic"
strictParameterNoneValue = false
include = [
    "cogs",
]
exclude = [
    "**/__pycache__",
    "build",
    "dist"
]

[tool.ruff]
line-length = 150
ignore = [
    "E501",  # Line too long
    "F403",  # Import star used
    "F405",  # Undefined name
    "E741",  # Ambiguous variable name
]
